/* eslint-disable react-hooks/rules-of-hooks */
import React from "react";
import Head from "next/head";
import style from "../../../styles/pages/loginStyle.module.scss";
import axios from "axios";
import { setCookie, getCookie } from "cookies-next";
import { useRouter } from "next/router";
import Link from "next/link";

export default function Recruiter() {
  const router = useRouter;
  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [isLoading, setIsLoading] = React.useState(false);
  const [error, setError] = React.useState(null);

  // React.useEffect(() => {
  //   console.log(getCookie("token"));
  // }, []);

  // React.useEffect(() => {
  //   let checkIsLogin = getCookie("token") && getCookie("profile");

  //   if (checkIsLogin) {
  //     router.replace("/");
  //   }
  // }, []);

  const handleSubmit = async () => {
    try {
      setIsLoading(true);

      const connect = await axios.post("/api/login", {
        email,
        password,
      });

      setIsLoading(false);
      setError(null);

      if (connect?.data?.data?.recruiter_id) {
        setCookie("token", connect?.data?.token);
        setCookie("profile", JSON.stringify(connect?.data?.data));
      } else {
        setError("Can't login in this area");
      }
    } catch (error) {
      setError(
        error?.response?.data?.messages ?? "Something wrong in our server"
      );
      setIsLoading(false);
    }
  };

  return (
    <>
      <Head>
        <title>Login Recruiter | Hire Job app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <div className="container-fluid">
          <div className="row">
            {/* SIDE-LEFT */}
            <div className={`col-6 ${style.colLeft}`}>
              <div className={style.overlay} />

              <div className={style.content}>
                <h1>
                  Temukan developer berbakat & terbaik
                  <br />
                  di berbagai bidang keahlian
                </h1>
              </div>
            </div>
            {/* SIDE-RIGHT */}
            <div className={`col-6 ${style.colRight}`}>
              <div className="mt-4 mb-0">
                <div className={style.title}>
                  <h2>Halo, Pewpeople</h2>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
                    euismod ipsum et dui rhoncus auctor.
                  </p>
                </div>
                {/* ALERT ERROR HANDLING */}
                <div className="alert-error">
                  {error ? (
                    <div
                      class="alert alert-danger text-center mb-3"
                      role="alert"
                      style={{
                        fontSize: "14px",
                        border: "0",
                        borderRadius: "15px",
                        marginBottom: "-15px",
                      }}
                    >
                      {error}
                    </div>
                  ) : null}
                </div>
                {/* FORM LOGIN */}
                <div className={style.form}>
                  <form>
                    <div className="mb-3">
                      <label for="exampleInputEmail1" class="form-label">
                        Email
                      </label>
                      <input
                        type="email"
                        class="form-control"
                        id="exampleInputEmail1"
                        aria-describedby="emailHelp"
                        placeholder="Masukan alamat email"
                        onChange={(e) => setEmail(e.target.value)}
                      />
                    </div>
                    <div className="mb-4">
                      <label for="exampleInputPassword1" className="form-label">
                        Kata Sandi
                      </label>
                      <input
                        type="password"
                        className="form-control"
                        id="exampleInputPassword1"
                        placeholder="Masukan kata sandi"
                        onChange={(e) => setPassword(e.target.value)}
                      />
                    </div>
                    {/* FORGOT PASSWORD */}
                    <div className={`mb-3 ${style.forgetPass}`}>
                      <p className="text-end">
                        <a>Lupa kata sandi?</a>
                      </p>
                    </div>
                    {/* BUTTON LOGIN */}
                    <div className={`d-grid gap-2 mb-4 ${style.btnLogin}`}>
                      <button
                        className="btn btn-warning"
                        type="button"
                        onClick={handleSubmit}
                        disabled={isLoading}
                      >
                        {isLoading ? "Loading..." : "Masuk"}
                      </button>
                    </div>
                    {/* REGISTER */}
                    <div className={`mt-3 register ${style.register}`}>
                      <p className="text-center">
                        Anda belum punya akun?{" "}
                        <Link
                          href={"/auth/register/recruiter"}
                          className="text-warning"
                        >
                          Masuk disini
                        </Link>
                      </p>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
