import React from "react";
import Head from "next/head";
import style from "../../../styles/pages/loginStyle.module.scss";

export default function worker() {
  return (
    <>
      <Head>
        <title>Login | Hire Job app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <div className="container-fluid">
          <div className="row">
            {/* SIDE-LEFT */}
            <div className={`col-6 ${style.colLeft}`}>
              <div className={style.overlay} />

              <div className={style.content}>
                <h1>
                  Temukan developer berbakat & terbaik
                  <br />
                  di berbagai bidang keahlian
                </h1>
              </div>
            </div>
            {/* SIDE-RIGHT */}
            <div className={`col-6 ${style.colRight}`}>
              <div className="mt-4 mb-0">
                <div className={style.title}>
                  <h2>Halo, Pewpeople</h2>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
                    euismod ipsum et dui rhoncus auctor.
                  </p>
                </div>
                {/* FORM LOGIN */}
                <div className={style.form}>
                  <form>
                    <div className="mb-3">
                      <label for="exampleInputEmail1" class="form-label">
                        Email
                      </label>
                      <input
                        type="email"
                        class="form-control"
                        id="exampleInputEmail1"
                        aria-describedby="emailHelp"
                        placeholder="Masukan alamat email"
                      />
                    </div>
                    <div className="mb-4">
                      <label for="exampleInputPassword1" className="form-label">
                        Kata Sandi
                      </label>
                      <input
                        type="password"
                        className="form-control"
                        id="exampleInputPassword1"
                        placeholder="Masukan kata sandi"
                      />
                    </div>
                    {/* FORGOT PASSWORD */}
                    <div className={`mb-3 ${style.forgetPass}`}>
                      <p className="text-end">
                        <a>Lupa kata sandi?</a>
                      </p>
                    </div>
                    {/* BUTTON LOGIN */}
                    <div className={`d-grid gap-2 mb-4 ${style.btnLogin}`}>
                      <button className="btn btn-warning" type="button">
                        Masuk
                      </button>
                    </div>
                    {/* REGISTER */}
                    <div className={`mt-3 register ${style.register}`}>
                      <p className="text-center">
                        Anda belum punya akun?{" "}
                        <a className="text-warning">Daftar disini</a>
                      </p>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
