/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import React from "react";
import style from "../../styles/pages/editStyle.module.scss";
import Navbar from "@/components/organisms/navbar";

export default function edit() {
  return (
    <>
      <Head>
        <title>edit | Hire Job app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <div className="container-fluid p-0">
          {/* NAVBAR sticky-top fixed-top */}
          <nav
            className={`container-fluid sticky-sm-top shadow ${style.containerNavbar}`}
          >
            <Navbar />
          </nav>
          {/* END OF NAVBAR */}

          {/* EDIT PROFILE */}
          <div className={`container-fluid px-0 ${style.editProfile}`}>
            {/* CARD HEAD */}
            <div
              className={`container p-0 pb-2 shadow-sm mb-4 ${style.cardHead}`}
            >
              <div className={style.overlay} />
              <div className={`row ${style.profilePhoto}`}>
                <div className="col-12 d-flex justify-content-center">
                  <img
                    className="rounded-circle"
                    src="/images/profile.webp"
                    alt="profile"
                  />
                </div>
              </div>
              <div className={`row ${style.profileData}`}>
                <div className="col-12 ">
                  <h2 className="text-center mb-2">Louis Tomlinsoon</h2>
                  <p className={`text-center mb-2 ${style.job}`}>
                    Web developer
                  </p>
                  <p className={`text-center ${style.addressProfession}`}>
                    Purwokerto, Jawa Tengah | Freelancer
                  </p>
                </div>
              </div>
              {/* BUTTON SAVE */}
              {/* <div className={`row mb-4 ${style.buttonHire}`}>
                <div className="d-grid gap-2 col-3 mx-auto ">
                  <button className="btn btn-warning" type="button">
                    Simpan
                  </button>
                </div>
              </div> */}
              {/* BUTTON CANCEL */}
              {/* <div className={`row mb-4 ${style.buttonHire}`}>
                <div className="d-grid gap-2 col-3 mx-auto ">
                  <button className="btn btn-warning" type="button">
                    Batal
                  </button>
                </div>
              </div> */}
            </div>
            {/* END OF CARD HEAD */}

            {/* EDIT PERSONAL DATA */}
            <div
              className={`container py-3 mb-4 shadow-sm ${style.cardPersonalData}`}
            >
              <div
                className={`row border-bottom border-2 py-3 ${style.subtitle}`}
              >
                <div className="col-12 d-flex justify-content-center">
                  <h4>Data diri</h4>
                </div>
              </div>
              {/* FORM */}
              <div className={`row pt-4 pb-1 mt-2 ${style.form}`}>
                <div className="col-6 px-5">
                  <label for="nama" class="form-label">
                    Nama lengkap
                  </label>
                  <input
                    type="text"
                    className="form-control mb-4"
                    id="nama"
                    aria-describedby="emailHelp"
                    placeholder="Masukan nama lengkap"
                  />
                  <label for="domisili" className="form-label">
                    Domisili
                  </label>
                  <input
                    type="text"
                    className="form-control"
                    id="domisili"
                    aria-describedby="emailHelp"
                    placeholder="Masukan domisili"
                  />
                </div>
                <div className="col-6 px-5">
                  <label for="jobDesk" className="form-label">
                    Job desk
                  </label>
                  <input
                    type="text"
                    className="form-control mb-4"
                    id="jobDesk"
                    aria-describedby="emailHelp"
                    placeholder="Masukan job desk"
                  />
                  <label for="TempatKerja" className="form-label">
                    Tempat kerja
                  </label>
                  <input
                    type="text"
                    className="form-control"
                    id="TempatKerja"
                    aria-describedby="emailHelp"
                    placeholder="Masukan tempat kerja"
                  />
                </div>
              </div>
              {/* DESKRIPSI SINGKAT */}
              <div className={`row py-4 mt-2 ${style.form}`}>
                <div className="col-12 px-5">
                  <label for="deskripsiSingkat" class="form-label">
                    Deskripsi singkat
                  </label>
                  <textarea
                    class="form-control"
                    id="deskripsiSingkat"
                    rows="3"
                    placeholder="Tuliskan deskripsi singkat"
                  ></textarea>
                </div>
              </div>
            </div>
            {/* END OF EDIT PERSONAL DATA */}

            {/* EDIT SKILLS */}
            <div
              className={`container py-3 shadow-sm mb-4 ${style.cardSkills}`}
            >
              <div
                className={`row border-bottom border-2 py-3 ${style.subtitle}`}
              >
                <div className="col-12 d-flex justify-content-center">
                  <h4>Skill</h4>
                </div>
              </div>
              {/* FORM SKILLS */}
              <div className={`row pt-4 pb-1 mt-2 ${style.skills}`}>
                <div className="col-12 px-5">
                  <input
                    type="text"
                    className="form-control mb-4"
                    id="nama"
                    aria-describedby="emailHelp"
                    placeholder="Example : JavaScript"
                  />
                </div>
              </div>
            </div>
            {/* END OF EDIT SKILLS */}

            {/* PENGALAMAN KERJA */}
            <div className={`container py-3 shadow-sm ${style.cardPengalaman}`}>
              <div
                className={`row border-bottom border-2 py-3 ${style.subtitle}`}
              >
                <div className="col-12 d-flex justify-content-center">
                  <h4>Pengalaman kerja</h4>
                </div>
              </div>
              {/* FORM POSISI */}
              <div className={`row pt-4 pb-1 mt-2 ${style.posisi}`}>
                <div className="col-12 px-5">
                  <label for="posisi" class="form-label">
                    Posisi
                  </label>
                  <input
                    type="text"
                    className="form-control mb-4"
                    id="posisi"
                    aria-describedby="emailHelp"
                    placeholder="Example : web developer"
                  />
                </div>
              </div>
              {/* FORM PERUSAHAAN & TAHUN/BULAN */}
              <div className={`row pb-1 mt-2 ${style.posisi}`}>
                <div className="col-6 px-5">
                  <label for="posisi" class="form-label">
                    Nama Perusahaan
                  </label>
                  <input
                    type="text"
                    className="form-control mb-4"
                    id="posisi"
                    aria-describedby="emailHelp"
                    placeholder="Example : PT ..."
                  />
                </div>
                <div className="col-6 px-5">
                  <label for="posisi" class="form-label">
                    Bulan/Tahun
                  </label>
                  <input
                    type="text"
                    className="form-control mb-4"
                    id="posisi"
                    aria-describedby="emailHelp"
                    placeholder="Example : 1 Januari 2023"
                  />
                </div>
              </div>
              {/* FORM DESKRIPSI */}
              <div className={`row pb-1 mt-2 ${style.posisi}`}>
                <div className="col-12 px-5">
                  <label for="deskripsiSingkat" class="form-label">
                    Deskripsi singkat
                  </label>
                  <textarea
                    class="form-control"
                    id="deskripsiSingkat"
                    rows="3"
                    placeholder="Deskripsi pekerjaan anda"
                  ></textarea>
                </div>
              </div>
              {/* BUTTON */}
              <div className={`row pb-1 mt-3 mb-4 ${style.button}`}>
                <div className="col-12 px-5 d-grid gap-2 col-6 mx-auto">
                  <button type="button" class="btn btn-outline-warning">
                    Tambahkan Pengalaman Kerja
                  </button>
                </div>
              </div>
            </div>
            {/* END OF PENGALAMAN KERJA */}
          </div>
          {/* END OF EDIT PROFILE */}
        </div>
      </main>
    </>
  );
}
