/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import React from "react";
import style from "../../styles/pages/hireStyle.module.scss";
import Navbar from "@/components/organisms/navbar";
import Footer from "@/components/organisms/footer";

export default function edit() {
  return (
    <>
      <Head>
        <title>edit | Hire Job app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <div className="container-fluid p-0">
          {/* NAVBAR sticky-top fixed-top */}
          <nav
            className={`container-fluid sticky-sm-top shadow ${style.containerNavbar}`}
          >
            <Navbar />
          </nav>
          {/* END OF NAVBAR */}

          {/* EDIT PROFILE */}
          <div className={`container-fluid px-0 ${style.profileCard}`}>
            
          </div>
          {/* END OF EDIT PROFILE */}

          {/* FOOTER */}
          <Footer />
          {/* END OF FOOTER */}
        </div>
      </main>
    </>
  );
}
