/* eslint-disable @next/next/no-img-element */
import React from "react";
import Head from "next/head";
import style from "../../styles/pages/listStyle.module.scss";
import Navbar from "@/components/organisms/navbar";
import Footer from "@/components/organisms/footer";

export default function list() {
  return (
    <>
      <Head>
        <title>Register | Hire Job app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <div className="container-fluid p-0">
          {/* NAVBAR sticky-top fixed-top */}
          <nav
            className={`container-fluid sticky-sm-top shadow-sm ${style.containerNavbar}`}
          >
            <Navbar />
          </nav>
          {/* END OF NAVBAR */}

          {/* TITLE BAR */}
          <section className={`container-fluid ${style.titleBar}`}>
            <div className={`container ${style.subtitle}`}>
              <h4>Top Jobs</h4>
            </div>
          </section>
          {/* END OF TITLE BAR */}

          {/* MAIN CONTENT */}
          <section className={`container-fluid ${style.mainPage}`}>
            {/* SEARCH & SORT BAR */}
            <div className={`container rounded-1 shadow-sm ${style.search}`}>
              <div className={`row`}>
                {/* FORM SEARCH */}
                <div
                  className={`col-9 border-end border-2 ${style.formSearch}`}
                >
                  <input
                    type="search"
                    className="form-control d-inline border-0"
                    id="exampleFormControlInput1"
                    placeholder="Search for any skill"
                  />
                </div>
                {/* BTN SORT */}
                <div className={`col-3 ${style.btnSort}`}>
                  <div
                    class="btn-group"
                    role="group"
                    aria-label="Basic radio toggle button group"
                  >
                    <select
                      className="form-select border-0"
                      aria-label="Default select example"
                    >
                      <option selected disabled>
                        Kategori
                      </option>
                      <option value="name_asc">Sortir berdasarkan nama</option>
                      <option value="name_desc">
                        Sortir berdasarkan Skill
                      </option>
                      <option value="release_asc">
                        Sortir berdasarkan Lokasi
                      </option>
                      <option value="release_desc">
                        Sortir berdasarkan freelance
                      </option>
                      <option value="release_desc">
                        Sortir berdasarkan fulltime
                      </option>
                    </select>
                    <button type="button" className="btn btn-primary rounded-1">
                      Search
                    </button>
                  </div>
                </div>
              </div>
            </div>
            {/* END OF SEARCH & SORT BAR */}

            {/* LIST WORKER */}
            <section
              className={`container mb-4 rounded-1 shadow-sm ${style.list}`}
            >
              <div className={`row d-flex align-items-center ${style.worker}`}>
                {/* PHOTO PROFILE */}
                <div className="col-1">
                  <img
                    className="rounded-circle border border-1"
                    src="/images/profile.webp"
                    alt="photo-profile"
                  />
                </div>
                {/* BRIEF DATA */}
                <div className="col-8 ms-4">
                  <div className={`${style.data}`}>
                    <h5>Louis Tomlinson</h5>
                    <p className="mb-2 d-block">Web developer</p>
                    <p>Web developer</p>
                    <button
                      type="button"
                      className={`btn btn-warning btn-sm me-2 ${style.badge}`}
                      disabled
                    >
                      JavaScript
                    </button>
                  </div>
                </div>
                {/* BUTTON TO PROFILE */}
                <div className="col-2">
                  <button type="button" class={`btn btn-primary ${style.btn}`}>
                    Lihat Profile
                  </button>
                </div>
              </div>
            </section>
            {/* END OF LIST WORKER */}

            {/* PAGINATION */}
            <div
              className={`container d-flex justify-content-center ${style.pagination}`}
            >
              <nav aria-label="Page navigation example">
                <ul class="pagination">
                  <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                    </a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="#">
                      1
                    </a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="#">
                      2
                    </a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="#">
                      3
                    </a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                      <span aria-hidden="true">&raquo;</span>
                    </a>
                  </li>
                </ul>
              </nav>
            </div>
            {/* END OF PAGINATION */}
          </section>
          {/* END OF MAIN CONTENT */}
          
          {/* FOOTER */}
          <Footer />
          {/* END OF FOOTER */}
        </div>
      </main>
    </>
  );
}
